# Generated by Django 5.1.4 on 2024-12-11 20:50

import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jt_webapp', '0002_user_certificate_earn_alter_user_business_brand_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='certificate_earn',
            field=models.ImageField(default='company', upload_to=django.contrib.auth.models.User),
        ),
    ]
